# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update serivce and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

OPENJDK_INSTALLER = struct(
    revision = "11.2.3-jdk11.0.1",
    sha256 = "232b1c3511f0d26e92582b7c3cc363be7ac633e371854ca2f2e9f2b50eb72a75",
)

OPENJDK_SRC = struct(
    revision = "11.2.3-jdk11.0.1",
    sha256 = "266efb8b8e51a2aff9026aba69ff75b6a9a1503729c74e03f7c0a5bb28684838",
)

DEBS_TARBALL = struct(
    revision = "20190131",
    sha256 = "6422d3e36597ff1b668d7cf2ffc36e6a2028a0ec8cd1f543c16509dd771d0315",
)

CACERTS = struct(
    revision = "20190131",
    sha256 = "c5a738711caed8b0d34aaad8da266c94d0ed147c03811e0738c20107db0e4f7a",
)
