dist: trusty
sudo: required
python:
  - "2.7"
os:
  - linux

jdk:
  - oraclejdk8  # Building Bazel requires JDK8.

language: go
go: 1.11.x
install: true

addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
      - bazel

install:
  - wget -q https://github.com/bazelbuild/buildtools/releases/download/0.20.0/buildifier
  - chmod +x ./buildifier

# Parallelize tests across virtual machines.
# https://docs.travis-ci.com/user/speeding-up-the-build/#parallelizing-your-builds-across-virtual-machines
env:
  - DISTRO=ubuntu1404
  - DISTRO=ubuntu1604

script:
  - set -e
  # Check for issues with the format of our bazel config files.
  - ./buildifier --version
  - ./buildifier --mode=check  $(find . -name BUILD -o -name WORKSPACE -o -name "*.bzl" -type f)
  - ./buildifier --lint=warn $(find . -name BUILD -o -name WORKSPACE -o -name "*.bzl" -type f)

  # Make sure all dependencies are properly specified and all targets are buildable.
  - bazel build //layers/$DISTRO/...
  - bazel test //layers/$DISTRO/... --test_output=errors
